### ISSUE TITLE
Default port in dockerfile not consistent with default in fastify library

### ISSUE THREAD

**Issue by zoe-codez** [Digital-Alchemy-TS/docker-standalone#8]
**Bug description**

https://github.com/Digital-Alchemy-TS/automation-standalone/blob/main/tools/docker/Dockerfile#L79
vs
https://github.com/Digital-Alchemy-TS/fastify/blob/main/src/fastify.module.ts#L43

**Comment by webbertakken** [comment]
Not sure this should be considered a bug.

Firstly because it's not common practice to change the default port of a container image, as it involves changing defaults on application level, which moves away from uniformity of all JavaScript apps (Bun or Node) being exposed at 3000 by default.

What's usually done instead is to have a mapping between docker port and publicly exposed port (e.g. port 3000 exposed at port 80). In fact, Fastly's official `quick start` example is using a node app that's following the port 3000 convention. 😄

Could you explain a bit more about what exactly [Digital-Alchemy-TS/fastify](https://github.com/Digital-Alchemy-TS/fastify) repo is responsible for and how it relates to this repo? I couldn't find much in the [docs](https://docs.digital-alchemy.app/fastify/) at the moment. And if indeed related, would it make sense to change the Fastify repo in favour of sticking closer to default ports in the JavaScript ecosystem instead?

**Comment by zoe-codez** [comment]
I consider the "bug" (for lack of a better word right now) the inconsistency in the default values, requiring additional configuration steps to match what would be the default exposed port. One extra gotcha to trip up on

That said, the bug is apparently on the wrapper library for not properly following conventions. Closing this issue and will put the patch in over there
